version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    depends_on: 
      - postgres
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    
volumes:
  pgdata:
